set(_AMENT_PACKAGE_NAME "elgamal_client")
set(elgamal_client_VERSION "0.0.1")
set(elgamal_client_MAINTAINER "lily <lily@example.com>")
set(elgamal_client_BUILD_DEPENDS "rclcpp" "std_msgs" "rm_server")
set(elgamal_client_BUILDTOOL_DEPENDS "ament_cmake")
set(elgamal_client_BUILD_EXPORT_DEPENDS "rclcpp" "std_msgs" "rm_server")
set(elgamal_client_BUILDTOOL_EXPORT_DEPENDS )
set(elgamal_client_EXEC_DEPENDS "rclcpp" "std_msgs" "rm_server")
set(elgamal_client_TEST_DEPENDS "ament_lint_auto" "ament_lint_common")
set(elgamal_client_GROUP_DEPENDS )
set(elgamal_client_MEMBER_OF_GROUPS )
set(elgamal_client_DEPRECATED "")
set(elgamal_client_EXPORT_TAGS)
list(APPEND elgamal_client_EXPORT_TAGS "<build_type>ament_cmake</build_type>")
